/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/banner.vue')['default']
    Bottom_mark: typeof import('./src/components/bottom_mark.vue')['default']
    Bottommark: typeof import('./src/components/bottommark.vue')['default']
    Central_region: typeof import('./src/components/central_region.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwich: typeof import('element-plus/es')['ElSwich']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Footer: typeof import('./src/components/footer.vue')['default']
    navigation: typeof import('./src/components/top navigation.vue')['default']
    Top_navigation: typeof import('./src/components/top_navigation.vue')['default']
    Topbanner: typeof import('./src/components/topbanner.vue')['default']
    Topnavigation: typeof import('./src/components/topnavigation.vue')['default']
  }
}
