/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/banner.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSwich: typeof import('element-plus/es')['ElSwich']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    navigation: typeof import('./src/components/top navigation.vue')['default']
    Top_navigation: typeof import('./src/components/top_navigation.vue')['default']
    Topbanner: typeof import('./src/components/topbanner.vue')['default']
    Topnavigation: typeof import('./src/components/topnavigation.vue')['default']
  }
}
